### ISSUE TITLE
Codegen Bug in OPTForCausalLM

### ISSUE THREAD

**Issue by kevinstephano** [csarofeen/pytorch#2076] opened 2022-10-14 22:37 UTC
### 🐛 Describe the bug

```
import torch
from torch._C._nvfuser import FusionDefinition, Fusion, DataType

def nvfuser_fusion_id0(fd : FusionDefinition) -> None :                    
    T0 = fd.define_tensor(symbolic_sizes=[-1, 1, -1, -1], contiguous=[True, False, False, True], dtype=DataType.Bool)
    T1 = fd.define_tensor(symbolic_sizes=[-1, -1, -1], contiguous=[True, True, True], dtype=DataType.Float)
    T2 = fd.define_tensor(symbolic_sizes=[-1, 1, -1, -1], contiguous=[True, True, True, True], dtype=DataType.Float)
    T3 = fd.ops.cast(T0, dtype=DataType.Float)
    T4 = fd.ops.view(T1, original_shape=[48, 128, 128], new_shape=[4, 12, 128, 128])
    S5 = fd.define_constant(1)
    T6 = fd.ops.mul(T3, S5)
    S7 = fd.define_constant(1.00000)
    T8 = fd.ops.sub(S7, T6)
    T9 = fd.ops.cast(T8, dtype=DataType.Bool)
    S10 = fd.define_constant(-3.40282e+38)
    T11 = fd.ops.where(T9, S10, T8)
    T12 = fd.ops.add(T11, T2)
    T13 = fd.ops.broadcast_in_dim(T12, output_shape=[4, 12, 128, 128], broadcast_dims=[0, 1, 2, 3])
    T14 = fd.ops.add(T4, T13)
    T15 = fd.ops.view(T14, original_shape=[4, 12, 128, 128], new_shape=[48, 128, 128])      
    T16 = fd.ops.max(T15, axes=[2], keepdim=False, dtype=DataType.Null)
    T17 = fd.ops.broadcast_in_dim(T16, output_shape=[48, 128, 1], broadcast_dims=[0, 1])
    T18 = fd.ops.broadcast_in_dim(T17, output_shape=[48, 128, 128], broadcast_dims=[0, 1, 2])
    T19 = fd.ops.sub(T15, T18)
    T20 = fd.ops.exp(T19)
    T21 = fd.ops.sum(T20, axes=[2], keepdim=False, dtype=DataType.Null)
    T22 = fd.ops.broadcast_in_dim(T21, output_shape=[48, 128, 1], broadcast_dims=[0, 1])
    T23 = fd.ops.broadcast_in_dim(T22, output_shape=[48, 128, 128], broadcast_dims=[0, 1, 2])
    T24 = fd.ops.div(T20, T23)
    fd.add_output(T12)
    fd.add_output(T24)

inputs = [
    torch.randn(4, 128, 1, 128, device='cuda').transpose(1,2),
    torch.randn(48, 128, 128, device='cuda'),
    torch.randn(4, 1, 128, 128, device='cuda'),
]

fs = Fusion()
with FusionDefinition(fs) as fd:
    nvfuser_fusion_id0(fd)

for _ in range(5) :
    fs.execute(inputs)
```
Error:
```
RuntimeError: index_map.find(root_dom[i]) != index_map.end() INTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/torch/csrc/jit/codegen/cuda/index_compute.cpp":2116, please report a bug to PyTorch. Couldn't find root mapping for T26_l[ iblockIdx.x318{( ceilDiv(( ( 4 * ( ceilDiv(T1.size[0], 4) ) ) * T0.size[2] ), blockDim.y) )}, ithreadIdx.y319{blockDim.y}, ithreadIdx.x325{( ceilDiv(( ceilDiv(( ceilDiv(T0.size[3], 4) ), 1) ), 1) )}, iUS324{1}, iV321{4}, iS322{1} ] ca_pos( 4 ) dim: 0 id: iS491{T1.size[0]}
```

### Versions

TOT

**Comment by csarofeen** [comment] 2022-10-15 14:06
Repros on view_reduction branch
```.cpp
TEST_F(NVFuserTest, FusionIssue2076_CUDA) {
  auto fusion_ptr = std::make_unique<Fusion>();
  Fusion& fusion = *fusion_ptr.get();
  FusionGuard fg(&fusion);

  // torch.randn(4, 128, 1, 128, device='cuda').transpose(1,2),
  auto tv0 = TensorViewBuilder()
                 .shape({-1, 1, -1, -1})
                 .dtype(DataType::Bool)
                 .contiguity({true, false, false, true})
                 .build();
  fusion.addInput(tv0);

  // torch.randn(48, 128, 128, device='cuda'),
  auto tv1 = makeContigTensor(3);
  fusion.addInput(tv1);

  // torch.randn(4, 1, 128, 128, device='cuda'),
  auto tv2 = makeContigConcreteTensor({-1, 1, -1, -1});
  fusion.addInput(tv2);

  auto tv3 = castOp(DataType::Float, tv0);
  auto tv4 = view(tv1, {48, 128, 128}, {4, 12, 128, 128});

  auto tv5 = mul(tv3, IrBuilder::create<Double>(1));
  auto tv6 = sub(IrBuilder::create<Double>(1), tv5);
  auto tv7 = castOp(DataType::Bool, tv6);
  auto tv8 =
      where(tv7, IrBuilder::create<Double>(-3.4028200000000001e+38), tv6);
  auto tv9 = add(tv8, tv2);
  auto tv10 = set(tv9);
  auto tv11 = expand(
      tv10,
      {tv10->axis(0)->extent(),
       IrBuilder::create<Int>(12),
       tv10->axis(2)->extent(),
       tv10->axis(3)->extent()});

  auto tv12 = add(tv4, tv11);
  auto tv13 = view(tv12, {4, 12, 128, 128}, {48, 128, 128});
  auto tv14 = max(tv13, {2});
  auto tv15 = broadcast(tv14, {false, false, true});
  auto tv16 = set(tv15);
  auto tv17 = expand(
      tv16,
      {tv16->axis(0)->extent(),
       tv16->axis(1)->extent(),
       IrBuilder::create<Int>(128)});
  auto tv18 = sub(tv13, tv17);
  auto tv19 = exp(tv18);
  auto tv20 = sum(tv19, {2});
  auto tv21 = broadcast(tv20, {false, false, true});
  auto tv22 = set(tv21);
  auto tv23 = expand(
      tv22,
      {tv22->axis(0)->extent(),
       tv22->axis(1)->extent(),
       IrBuilder::create<Int>(128)});
  auto tv24 = div(tv19, tv23);

  fusion.addOutput(tv9);
  fusion.addOutput(tv24);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);

  at::Tensor t0 =
      at::randn({4, 128, 1, 128}, options).transpose(1, 2).to(at::kBool);
  at::Tensor t1 = at::randn({48, 128, 128}, options);
  at::Tensor t2 = at::randn({4, 1, 128, 128}, options);

  auto t3 = t0.to(at::kFloat);
  auto t4 = t1.view({4, 12, 128, 128});

  // [4, 1, 128, 128]
  auto t5 = t3 * 1;
  auto t6 = 1 - t5;
  auto t7 = t6.to(at::kBool);
  auto t8 = at::where(t7, -3.4028200000000001e+38, t6);
  auto t9 = t8 + t2;
  auto t10 = t9;
  // [4, 1, 128, 128]
  auto t11 = t10.expand({4, 12, 128, 128});

  auto t12 = t4 + t11;
  auto t13 = t12.view({48, 128, 128});
  // 48, 128, 128
  auto t14 = std::get<0>(t13.max({2}));
  auto t15 = t14.unsqueeze(-1);
  // 48, 128, 1
  auto t16 = t15;
  auto t17 = t16.expand({48, 128, 128});
  auto t18 = t13 - t17;
  auto t19 = t18.exp();
  auto t20 = t19.sum({2});
  auto t21 = t20.unsqueeze(-1);
  auto t22 = t21;
  auto t23 = t22.expand({48, 128, 128});
  auto t24 = t19 / t23;

  FusionExecutorCache executor_cache(std::move(fusion_ptr));
  auto cg_outputs = executor_cache.runFusionWithInputs({t0, t1, t2});
  testValidate(&fusion, cg_outputs, {t0, t1, 2}, {t9, t24}, __LINE__, __FILE__);
}
```

**Comment by csarofeen** [comment] 2022-10-15 14:45
This bug might be a challenging one.

**Comment by csarofeen** [comment] 2022-10-16 16:39
I think what's happening is we're going back through one path in indexing, but not the one we need, so we're getting into the wrong view branch to index into a tensor.

Simpler repro, indexing fails on T11
```.cpp
// Simplify first to reproduce compute at issue
TEST_F(NVFuserTest, FusionIssue2076_v2_CUDA) {
  auto fusion_ptr = std::make_unique<Fusion>();
  Fusion& fusion = *fusion_ptr.get();
  FusionGuard fg(&fusion);

  // torch.randn(4, 128, 1, device='cuda').transpose(1,2)
  auto tv0 = TensorViewBuilder()
                 .shape({-1, 1, -1})
                 .contiguity({true, false, false})
                 .build();
  fusion.addInput(tv0);

  // torch.randn(48, 128, device='cuda')
  auto tv1 = makeContigTensor(2);
  fusion.addInput(tv1);

  // torch.randn(4, 1, 128, device='cuda'),
  auto tv2 = makeContigConcreteTensor({-1, 1, -1});
  fusion.addInput(tv2);

  auto tv3 = view(tv1, {48, 128}, {4, 12, 128});
  auto tv4 = add(tv0, tv2);
  
  auto tv5 = add(tv3, tv4);
  auto tv6 = view(tv5, {4, 12, 128}, {48, 128});
  auto tv7 = sum(tv6, {1});
  auto tv8 = broadcast(tv7, {false, true});
  auto tv9 = add(tv6, tv8);

  fusion.addOutput(tv4);
  fusion.addOutput(tv9);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);

  at::Tensor t0 =
      at::randn({4, 128, 1}, options).transpose(1, 2);
  at::Tensor t1 = at::randn({48, 128}, options);
  at::Tensor t2 = at::randn({4, 1, 128}, options);

  auto t3 = t1.view({4, 12, 128});

  // [4, 1, 128, 128]
  auto t4 = t0.add(t2);
  auto t5 = t3.add(t4);
  auto t6 = t5.view({48, 128});
  auto t7 = t6.sum({1});
  auto t8 = t7.unsqueeze(-1);
  auto t9 = t6.add(t8);

  FusionExecutorCache executor_cache(std::move(fusion_ptr));
  auto cg_outputs = executor_cache.runFusionWithInputs({t0, t1, t2});
  testValidate(&fusion, cg_outputs, {t0, t1, 2}, {t4, t9}, __LINE__, __FILE__);
}
```

**Comment by csarofeen** [comment] 2022-10-16 16:52
This is result of a mistake in concrete ID selection. Strange how much other stuff worked with the issue.

We effectively have:
```
T3[4, 12, 128] = T1[48, 128]
T5[4, 12, 128] = T0[4, 1, 128] * T3[4, 12, 128]
T6[48, 128]
```
So when we want the concrete ID of the permissive map on `T6`'s dim of `48` we traverse back into `T1`'s `48` and `T3`'s `4`, and `b1`. Since the algorithm just looks at the count, it thinks `T3`'s the right concrete path since it has one iteration domain and one broadcast domain, but `T1` only has the one iteration domain, so the tie is split by the extra broadcast. This is wrong.

**Comment by jjsjann123** [comment] 2022-10-17 22:55
Note: the repro here is wrong, first argument `torch.randn(4, 128, 1, 128, device='cuda').transpose(1,2),` -> should be converted to `.bool()`

**Comment by jjsjann123** [comment] 2022-10-17 22:55
This one is fixed in #2089

**Comment by csarofeen** [comment] 2022-10-18 11:49
> Note: the repro here is wrong, first argument `torch.randn(4, 128, 1, 128, device='cuda').transpose(1,2),` -> should be converted to `.bool()`

Yeah, I caught that in the first C++ repro I added, though it's not necessary to reproduce the issue which is the trimmed down second repro I added.

**Comment by csarofeen** [comment] 2023-01-03 13:42
@liqiangxl could you please check this repro and see if it still fails on devel? I lost track of this one.

**Comment by liqiangxl** [comment] 2023-01-04 16:32
This bug is fixed on devel. There is no error after changing the input of the python script to:
```
inputs = [
    torch.randn(4, 128, 1, 128, device='cuda').transpose(1,2).to(bool),
    torch.randn(48, 128, 128, device='cuda'),
    torch.randn(4, 1, 128, 128, device='cuda'),
]
```

**Comment by kevinstephano** [comment] 2023-01-04 17:58
Thanks for checking.  Let's close then...

**Closed as completed** 2023-01-04 17:58 UTC
