### ISSUE TITLE
Index fix breaks CI test testGPU_FusionSmemBlockGemmCache

### ISSUE THREAD

**Issue by jjsjann123** [csarofeen/pytorch#298] opened 2020-08-15 23:27 UTC
## 🐛 Bug

Title is pretty self explanatory :)

The only reason opening the issue is that we macro-out the test in https://github.com/csarofeen/pytorch/pull/295 which silently turns the test into a no-op instead of properly throwing out errors.

Leaving the issue here just so that we would not forgot to re-visit this and make sure it's properly fixed.

**Comment by csarofeen** [comment] 2020-08-20 12:23
Duplicate of https://github.com/csarofeen/pytorch/issues/296

**Closed as completed by csarofeen** 2020-08-20 12:23 UTC
