### ISSUE TITLE
[in-place BN fw/bw] BN forward codegen error

### ISSUE THREAD

**Issue by jjsjann123** [csarofeen/pytorch#715] opened 2021-03-05 23:24 UTC
## 🐛 Bug

I'm still seeing this error in https://github.com/csarofeen/pytorch/tree/bn_error_0

Build and run the test in below vvv:

```
root@5d47ee14409b:/volume/codegen_project/pytorch_codegen/build/bin# ./test_jit --gtest_filter="*FusionBNRepro*"
Note: Google Test filter = *FusionBNRepro*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from NVFuserTest
[ RUN      ] NVFuserTest.FusionBNRepro_CUDA
unknown file: Failure
C++ exception with description "falseINTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/root_domain_map.cpp":486, please report a bug to PyTorch. Mapping IterDomain iS33{i1} of [ iS131{( ceilDiv(i3, blockDim.y) )}, iS132{blockDim.y}, iS138{blockDim.x}, iS137{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS136{4} ] not possible as it would require recomputing the source tensor. Producer root: bS17{1} iS16{i3} bS18{1} bS19{1}. Consumer root: iS33{i1} iS34{i3} iS35{i5} iS36{i7}. Mapping: {
        { {[ iblockIdx.x116{( ceilDiv(i3, blockDim.y) )}, ithreadIdx.y117{blockDim.y}, rthreadIdx.x118{blockDim.x} ] (root: iS115{i3} rthreadIdx.x118{blockDim.x}, maybe rfactor: iS115{i3} rthreadIdx.x118{blockDim.x}), rthreadIdx.x118{blockDim.x}} {[ iS107{( ceilDiv(i3, blockDim.y) )}, iS108{blockDim.y}, iS114{blockDim.x}rf, rS113{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}rf, rUR112{4}rf ] (root: rS103{i1}rf iS104{i3} rS105{i5}rf rS106{i7}rf, maybe rfactor: iS104{i3} rS113{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}rf iS114{blockDim.x}rf rUR112{4}rf), iS114{blockDim.x}rf} }
        { {[ bS17{1}, iS16{i3}, bS18{1}, bS19{1} ] (root: bS17{1} iS16{i3} bS18{1} bS19{1}, maybe rfactor: bS17{1} iS16{i3} bS18{1} bS19{1}), bS18{1} (rS87{1})} {[ bS12{1}, iS13{i3}, bS14{1}, bS15{1} ] (root: bS12{1} iS13{i3} bS14{1} bS15{1}, maybe rfactor: bS12{1} iS13{i3} bS14{1} bS15{1}), bS14{1} (rS87{1})} {[ rS85{1}, iS86{i3}, rS87{1}, rS88{1} ] (root: rS85{1} iS86{i3} rS87{1} rS88{1}, maybe rfactor: rS85{1} iS86{i3} rS87{1} rS88{1}), rS87{1}} }
        { {[ bS12{1}, iS13{i3}, bS14{1}, bS15{1} ] (root: bS12{1} iS13{i3} bS14{1} bS15{1}, maybe rfactor: bS12{1} iS13{i3} bS14{1} bS15{1}), bS15{1} (rS88{1})} {[ rS85{1}, iS86{i3}, rS87{1}, rS88{1} ] (root: rS85{1} iS86{i3} rS87{1} rS88{1}, maybe rfactor: rS85{1} iS86{i3} rS87{1} rS88{1}), rS88{1}} {[ bS17{1}, iS16{i3}, bS18{1}, bS19{1} ] (root: bS17{1} iS16{i3} bS18{1} bS19{1}, maybe rfactor: bS17{1} iS16{i3} bS18{1} bS19{1}), bS19{1} (rS88{1})} }
        { {[ bS21{1}, iS20{i3}, bS22{1}, bS23{1} ] (root: bS21{1} iS20{i3} bS22{1} bS23{1}, maybe rfactor: bS21{1} iS20{i3} bS22{1} bS23{1}), bS22{1} (bS32{1})} {[ bS25{1}, bS26{1}, bS27{1}, iS28{i13} ] (root: bS25{1} bS26{1} bS27{1} iS28{i13}, maybe rfactor: bS25{1} bS26{1} bS27{1} iS28{i13}), bS27{1} (bS32{1})} {[ b
S17{1}, iS16{i3}, bS18{1}, bS19{1} ] (root: bS17{1} iS16{i3} bS18{1} bS19{1}, maybe rfactor: bS17{1} iS16{i3} bS18{1} bS19{1}), bS18{1} (bS32{1})} {[ bS31{1}, iS30{i3}, bS32{1}, iS29{i13} ] (root: bS31{1} iS30{i3} bS32{1} iS29{i13}, maybe rfactor: bS31{1} iS30{i3} bS32{1} iS29{i13}), bS32{1} (bS32{1})} {[ bS12{1}, iS1
3{i3}, bS14{1}, bS15{1} ] (root: bS12{1} iS13{i3} bS14{1} bS15{1}, maybe rfactor: bS12{1} iS13{i3} bS14{1} bS15{1}), bS14{1} (bS32{1})} }
        { {[ rS85{1}, iS86{i3}, rS87{1}, rS88{1} ] (root: rS85{1} iS86{i3} rS87{1} rS88{1}, maybe rfactor: rS85{1} iS86{i3} rS87{1} rS88{1}), rS85{1}} {[ bS12{1}, iS13{i3}, bS14{1}, bS15{1} ] (root: bS12{1} iS13{i3} bS14{1} bS15{1}, maybe rfactor: bS12{1} iS13{i3} bS14{1} bS15{1}), bS12{1} (rS85{1})} {[ bS17{1}, iS16{i3}, bS18{1}, bS19{1} ] (root: bS17{1} iS16{i3} bS18{1} bS19{1}, maybe rfactor: bS17{1} iS16{i3} bS18{1} bS19{1}), bS17{1} (rS85{1})} }
        { {[ bS17{1}, iS16{i3}, bS18{1}, bS19{1} ] (root: bS17{1} iS16{i3} bS18{1} bS19{1}, maybe rfactor: bS17{1} iS16{i3} bS18{1} bS19{1}), iS16{i3}} {[ iS123{( ceilDiv(i3, blockDim.y) )}, iS124{blockDim.y}, iS130{blockDim.x}, iS129{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS128{4} ] (root: iS37{i1} iS38{i3} iS39{i5} iS40{i7}, maybe rfactor: iS37{i1} iS38{i3} iS39{i5} iS40{i7}), iS38{i3}} {[ iblockIdx.x116{( ceilDiv(i3, blockDim.y) )}, ithreadIdx.y117{blockDim.y}, rthreadIdx.x118{blockDim.x} ] (root: iS115{i3} rthreadIdx.x118{blockDim.x}, maybe rfactor: iS115{i3} rthreadIdx.x118{blockDim.x}), iS115{i3}} {[ rS85{1}, iS86{i3}, rS87{1}, rS88{1} ] (root: rS85{1} iS86{i3} rS87{1} rS88{1}, maybe rfactor: rS85{1} iS86{i3} rS87{1} rS88{1}), iS86{i3}} {[ iS7{i15} ] (root: iS7{i15}, maybe rfactor: iS7{i15}), iS7{i15}} {[ bS12{1}, iS13{i3}, bS14{1}, bS15{1} ] (root: bS12{1} iS13{i3} bS14{1} bS15{1}, maybe rfactor: bS12{1} iS13{i3} bS14{1} bS15{1}), iS13{i3}} {[ bS25{1}, bS26{1}, bS27{1}, iS28{i13} ] (root: bS25{1} bS26{1} bS27{1} iS28{i13}, maybe rfactor: bS25{1} bS26{1} bS27{1} iS28{i13}), bS26{1} (iS30{i3})} {[ iS139{( ceilDiv(i3, blockDim.y) )}, iS140{blockDim.y}, iS146{blockDim.x}, iS145{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS144{4} ] (root: iS0{i1} iS1{i3} iS2{i5} iS3{i7}, maybe rfactor: iS0{i1} iS1{i3} iS2{i5} iS3{i7}), iS1{i3}} {[ iS131{( ceilDiv(i3, blockDim.y) )}, iS132{blockDim.y}, iS138{blockDim.x}, iS137{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS136{4} ] (root: iS33{i1} iS34{i3} iS35{i5} iS36{i7}, maybe rfactor: iS33{i1} iS34{i3} iS35{i5} iS36{i7}), iS34{i3}} {[ iS131{( ceilDiv(i3, blockDim.y) )}, iS132{blockDim.y}, iS138{blockDim.x}, iS137{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS136{4} ] (root: iS33{i1} iS34{i3} iS35{i5} iS36{i7}, maybe rfactor: iS33{i1} iS34{i3} iS35{i5} iS36{i7}), iS34{i3}} {[ iS55{i15} ] (root: iS55{i15}, maybe rfactor: iS55{i15}), iS55{i15}} {[ iS121{( ceilDiv(i3, blockDim.y) )}, iS122{blockDim.y} ] (root: iS53{i3}, maybe rfactor: iS53{i3}), iS53{i3}} {[ iS123{( ceilDiv(i3, blockDim.y) )}, iS124{blockDim.y}, iS130{blockDim.x}, iS129{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS128{4} ] (root: iS37{i1} iS38{i3} iS39{i5} iS40{i7}, maybe rfactor: iS37{i1} iS38{i3} iS39{i5} iS40{i7}), iS38{i3}} {[ iS107{( ceilDiv(i3, blockDim.y) )}, iS108{blockDim.y}, iS114{blockDim.x}rf, rS113{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}rf, rUR112{4}rf ] (root: rS103{i1}rf iS104{i3} rS105{i5}rf rS106{i7}rf, maybe rfactor: iS104{i3} rS113{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}rf iS114{blockDim.x}rf rUR112{4}rf), iS104{i3}} {[ iblockIdx.x101{( ceilDiv(i15, blockDim.y) )}, ithreadIdx.y102{blockDim.y} ] (root: iS56{i15}, maybe rfactor: iS56{i15}), iS56{i15}} {[ bS21{1}, iS20{i3}, bS22{1}, bS23{1} ] (root: bS21{1} iS20{i3} bS22{1} bS23{1}, maybe rfactor: bS21{1} iS20{i3} bS22{1} bS23{1}), iS20{i3}} {[ bS31{1}, iS30{i3}, bS32{1}, iS29{i13} ] (root: bS31{1} iS30{i3} bS32{1} iS29{i13}, maybe rfactor: bS31{1} iS30{i3} bS32{1} iS29{i13}), iS30{i3}} {[ iS119{( ceilDiv(i3, blockDim.y) )}, iS120{blockDim.y} ] (root: iS54{i3}, maybe rfactor: iS54{i3}), iS54{i3}} }
        { {[ iS131{( ceilDiv(i3, blockDim.y) )}, iS132{blockDim.y}, iS138{blockDim.x}, iS137{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS136{4} ] (root: iS33{i1} iS34{i3} iS35{i5} iS36{i7}, maybe rfactor: iS33{i1} iS34{i3} iS35{i5} iS36{i7}), iS36{i7}} {[ iS123{( ceilDiv(i3, blockDim.y) )}, iS124{blockDim.y}, iS130{blockDim.x}, iS129{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS128{4} ] (root: iS37{i1} iS38{i3} iS39{i5} iS40{i7}, maybe rfactor: iS37{i1} iS38{i3} iS39{i5} iS40{i7}), iS40{i7}} {[ bS17{1}, iS16{i3}, bS18{1}, bS19{1} ] (root: bS17{1} iS16{i3} bS18{1} bS19{1}, maybe rfactor: bS17{1} iS16{i3} bS18{1} bS19{1}), bS19{1} (iS36{i7})} {[ iS123{( ceilDiv(i3, blockDim.y) )}, iS124{blockDim.y}, iS130{blockDim.x}, iS129{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS128{4} ] (root: iS37{i1} iS38{i3} iS39{i5} iS40{i7}, maybe rfactor: iS37{i1} iS38{i3} iS39{i5} iS40{i7}), iS40{i7}} {[ bS12{1}, iS13{i3}, bS14{1}, bS15{1} ] (root: bS12{1} iS13{i3} bS14{1} bS15{1}, maybe rfactor: bS12{1} iS13{i3} bS14{1} bS15{1}), bS15{1} (iS36{i7})} {[ iS139{( ceilDiv(i3, blockDim.y) )}, iS140{blockDim.y}, iS146{blockDim.x}, iS145{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS144{4} ] (root: iS0{i1} iS1{i3} iS2{i5} iS3{i7}, maybe rfactor: iS0{i1} iS1{i3} iS2{i5} iS3{i7}), iS3{i7}} {[ iS131{( ceilDiv(i3, blockDim.y) )}, iS132{blockDim.y}, iS138{blockDim.x}, iS137{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS136{4} ] (root: iS33{i1} iS34{i3} iS35{i5} iS36{i7}, maybe rfactor: iS33{i1} iS34{i3} iS35{i5} iS36{i7}), iS36{i7}} {[ iS107{( ceilDiv(i3, blockDim.y) )}, iS108{blockDim.y}, iS114{blockDim.x}rf, rS113{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}rf, rUR112{4}rf ] (root: rS103{i1}rf iS104{i3} rS105{i5}rf rS106{i7}rf, maybe rfactor: iS104{i3} rS113{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}rf iS114{blockDim.x}rf rUR112{4}rf), rS106{i7}rf} }
        { {[ iS139{( ceilDiv(i3, blockDim.y) )}, iS140{blockDim.y}, iS146{blockDim.x}, iS145{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS144{4} ] (root: iS0{i1} iS1{i3} iS2{i5} iS3{i7}, maybe rfactor: iS0{i1} iS1{i3} iS2{i5} iS3{i7}), iS2{i5}} {[ bS17{1}, iS16{i3}, bS18{1}, bS19{1} ] (root: bS17{1} iS16{i3} bS18{1} bS19{1}, maybe rfactor: bS17{1} iS16{i3} bS18{1} bS19{1}), bS18{1} (iS35{i5})} {[ iS123{( ceilDiv(i3, blockDim.y) )}, iS124{blockDim.y}, iS130{blockDim.x}, iS129{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS128{4} ] (root: iS37{i1} iS38{i3} iS39{i5} iS40{i7}, maybe rfactor: iS37{i1} iS38{i3} iS39{i5} iS40{i7}), iS39{i5}} {[ iS123{( ceilDiv(i3, blockDim.y) )}, iS124{blockDim.y}, iS130{blockDim.x}, iS129{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS128{4} ] (root: iS37{i1} iS38{i3} iS39{i5} iS40{i7}, maybe rfactor: iS37{i1} iS38{i3} iS39{i5} iS40{i7}), iS39{i5}} {[ bS12{1}, iS13{i3}, bS14{1}, bS15{1} ] (root: bS12{1} iS13{i3} bS14{1} bS15{1}, maybe rfactor: bS12{1} iS13{i3} bS14{1} bS15{1}), bS14{1} (iS35{i5})} {[ iS131{( ceilDiv(i3, blockDim.y) )}, iS132{blockDim.y}, iS138{blockDim.x}, iS137{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS136{4} ] (root: iS33{i1} iS34{i3} iS35{i5} iS36{i7}, maybe rfactor: iS33{i1} iS34{i3} iS35{i5} iS36{i7}), iS35{i5}} {[ iS131{( ceilDiv(i3, blockDim.y) )}, iS132{blockDim.y}, iS138{blockDim.x}, iS137{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS136{4} ] (root: iS33{i1} iS34{i3} iS35{i5} iS36{i7}, maybe rfactor: iS33{i1} iS34{i3} iS35{i5} iS36{i7}), iS35{i5}} {[ iS107{( ceilDiv(i3, blockDim.y) )}, iS108{blockDim.y}, iS114{blockDim.x}rf, rS113{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}rf, rUR112{4}rf ] (root: rS103{i1}rf iS104{i3} rS105{i5}rf rS106{i7}rf, maybe rfactor: iS104{i3} rS113{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}rf iS114{blockDim.x}rf rUR112{4}rf), rS105{i5}rf} }
        { {[ bS21{1}, iS20{i3}, bS22{1}, bS23{1} ] (root: bS21{1} iS20{i3} bS22{1} bS23{1}, maybe rfactor: bS21{1} iS20{i3} bS22{1} bS23{1}), bS21{1} (bS31{1})} {[ bS31{1}, iS30{i3}, bS32{1}, iS29{i13} ] (root: bS31{1} iS30{i3} bS32{1} iS29{i13}, maybe rfactor: bS31{1} iS30{i3} bS32{1} iS29{i13}), bS31{1} (bS31{1})} {[ bS25{1}, bS26{1}, bS27{1}, iS28{i13} ] (root: bS25{1} bS26{1} bS27{1} iS28{i13}, maybe rfactor: bS25{1} bS26{1} bS27{1} iS28{i13}), bS25{1} (bS31{1})} {[ bS17{1}, iS16{i3}, bS18{1}, bS19{1} ] (root: bS17{1} iS16{i3} bS18{1} bS19{1}, maybe rfactor: bS17{1} iS16{i3} bS18{1} bS19{1}), bS17{1} (bS31{1})} {[ bS12{1}, iS13{i3}, bS14{1}, bS15{1} ] (root: bS12{1} iS13{i3} bS14{1} bS15{1}, maybe rfactor: bS12{1} iS13{i3} bS14{1} bS15{1}), bS12{1} (bS31{1})} }
        { {[ bS17{1}, iS16{i3}, bS18{1}, bS19{1} ] (root: bS17{1} iS16{i3} bS18{1} bS19{1}, maybe rfactor: bS17{1} iS16{i3} bS18{1} bS19{1}), bS17{1} (iS33{i1})} {[ iS139{( ceilDiv(i3, blockDim.y) )}, iS140{blockDim.y}, iS146{blockDim.x}, iS145{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS144{4} ] (root: iS0{i1} iS1{i3} iS2{i5} iS3{i7}, maybe rfactor: iS0{i1} iS1{i3} iS2{i5} iS3{i7}), iS0{i1}} {[ iS123{( ceilDiv(i3, blockDim.y) )}, iS124{blockDim.y}, iS130{blockDim.x}, iS129{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS128{4} ] (root: iS37{i1} iS38{i3} iS39{i5} iS40{i7}, maybe rfactor: iS37{i1} iS38{i3} iS39{i5} iS40{i7}), iS37{i1}} {[ iS131{( ceilDiv(i3, blockDim.y) )}, iS132{blockDim.y}, iS138{blockDim.x}, iS137{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS136{4} ] (root: iS33{i1} iS34{i3} iS35{i5} iS36{i7}, maybe rfactor: iS33{i1} iS34{i3} iS35{i5} iS36{i7}), iS33{i1}} {[ iS123{( ceilDiv(i3, blockDim.y) )}, iS124{blockDim.y}, iS130{blockDim.x}, iS129{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS128{4} ] (root: iS37{i1} iS38{i3} iS39{i5} iS40{i7}, maybe rfactor: iS37{i1} iS38{i3} iS39{i5} iS40{i7}), iS37{i1}} {[ iS131{( ceilDiv(i3, blockDim.y) )}, iS132{blockDim.y}, iS138{blockDim.x}, iS137{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}, iS136{4} ] (root: iS33{i1} iS34{i3} iS35{i5} iS36{i7}, maybe rfactor: iS33{i1} iS34{i3} iS35{i5} iS36{i7}), iS33{i1}} {[ bS12{1}, iS13{i3}, bS14{1}, bS15{1} ] (root: bS12{1} iS13{i3} bS14{1} bS15{1}, maybe rfactor: bS12{1} iS13{i3} bS14{1} bS15{1}), bS12{1} (iS33{i1})} {[ iS107{( ceilDiv(i3, blockDim.y) )}, iS108{blockDim.y}, iS114{blockDim.x}rf, rS113{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}rf, rUR112{4}rf ] (root: rS103{i1}rf iS104{i3} rS105{i5}rf rS106{i7}rf, maybe rfactor: iS104{i3} rS113{( ceilDiv(( ceilDiv(( i1 * ( i5 * i7 ) ), 4) ), blockDim.x) )}rf iS114{blockDim.x}rf rUR112{4}rf), rS103{i1}rf} }
        { {[ bS31{1}, iS30{i3}, bS32{1}, iS29{i13} ] (root: bS31{1} iS30{i3} bS32{1} iS29{i13}, maybe rfactor: bS31{1} iS30{i3} bS32{1} iS29{i13}), iS29{i13}} {[ bS25{1}, bS26{1}, bS27{1}, iS28{i13} ] (root: bS25{1} bS26{1} bS27{1} iS28{i13}, maybe rfactor: bS25{1} bS26{1} bS27{1} iS28{i13}), iS28{i13}} {[ iS24{i13} ] (root: iS24{i13}, maybe rfactor: iS24{i13}), iS24{i13}} {[ bS12{1}, iS13{i3}, bS14{1}, bS15{1} ] (root: bS12{1} iS13{i3} bS14{1} bS15{1}, maybe rfactor: bS12{1} iS13{i3} bS14{1} bS15{1}), bS15{1} (iS29{i13})} {[ bS17{1}, iS16{i3}, bS18{1}, bS19{1} ] (root: bS17{1} iS16{i3} bS18{1} bS19{1}, maybe rfactor: bS17{1} iS16{i3} bS18{1} bS19{1}), bS19{1} (iS29{i13})} {[ bS21{1}, iS20{i3}, bS22{1}, bS23{1} ] (root: bS21{1} iS20{i3} bS22{1} bS23{1}, maybe rfactor: bS21{1} iS20{i3} bS22{1} bS23{1}), bS23{1} (iS29{i13})} {[ iS6{i13} ] (root: iS6{i13}, maybe rfactor: iS6{i13}), iS6{i13}} }
}
```

**Comment by jjsjann123** [comment] 2021-03-06 01:23
I think Shiming is working on this, tagging @shmsong @naoyam

**Comment by naoyam** [comment] 2021-03-06 01:34
I got a different result:
```
C++ exception with description "out->getValType() == ValType::TensorViewINTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/executor.cpp":111, please report a bug to PyTorch. Output types from fusions that are not tensors are not supported at this point.
Exception raised from compileFusion at ../torch/csrc/jit/codegen/cuda/executor.cpp:111 (most recent call first):
```

I used commit 05e268d113d26ce2f90dfb3a3c23b137a4dd03ec

**Comment by shmsong** [comment] 2021-03-07 07:05
This error will be consistently shown after #719

**Comment by shmsong** [comment] 2021-03-07 07:09
Root cause of the root domain error found. It's indeed real. Here is the very minimum repro of root cause:

```cpp
TEST(NVFuserTest, FusionSmallRepro_CUDA) {
  Fusion fusion;
  FusionGuard fg(&fusion);

  auto tv0 = makeSymbolicTensor(1);
  auto tv1 = makeSymbolicTensor(2);

  fusion.addInput(tv0);
  fusion.addInput(tv1);

  auto tv2 = broadcast(tv0,{true,false});
  auto tv3 = sum(tv2,{0});
  auto tv4 = add(tv2,tv1);

  fusion.addOutput(tv3);
  fusion.addOutput(tv4);

  ComputeAtRootDomainMap map;
  map.build();

  checkIdMapped(map, tv2, tv2->getRootDomain()[0], tv4, tv4->getRootDomain()[0], true);

}
```

Essentially two concretized versions of the same broadcast axis don't know each other and one ended up killing the other here:

[https://github.com/csarofeen/pytorch/blob/20_12_3_devel/torch/csrc/jit/codegen/cuda/root_domain_map.cpp#L313-L316](https://github.com/csarofeen/pytorch/blob/20_12_3_devel/torch/csrc/jit/codegen/cuda/root_domain_map.cpp#L313-L316)

**Comment by csarofeen** [comment] 2022-01-20 22:32
Closing as repro no longer repros.

**Closed as completed by csarofeen** 2022-01-20 22:32 UTC
