### ISSUE TITLE
Error with expanded input + softmax and softmax_backward

### ISSUE THREAD

**Issue by Chillee** [csarofeen/pytorch#1416] opened 2022-01-28 02:23 UTC
```
inps = [(40*16, 256, 256), (40*16, 256, 256)]

inps = [torch.randn(i, device='cuda', requires_grad=False) for i in inps]
inps[1] = torch.randn((), device='cuda').expand(40*16, 256, 256)
def forward(primals_1, tangents_1):
    _softmax = torch.ops.aten._softmax(primals_1, -1, False);  primals_1 = None
    _softmax_backward_data = torch.ops.aten._softmax_backward_data(tangents_1, _softmax, -1, 6);  tangents_1 = _softmax = None
    return [_softmax_backward_data, None]

f = torch.jit.script(forward)
with torch.jit.fuser("fuser2"):
  for _ in range(10):
    f(*inps)
```

```
RuntimeError: Attempting to bind T0.size[0] to 640but it's already set to 256
```

**Comment by naoyam** [comment] 2022-01-28 18:04
@Chillee, thanks for reporting the error. I looked at the repro, and it does reproduce on my side as well.

It seems that two Aten tensors of `([640, 256, 256], `[640, 256, 256])` are passed, but at the time `bindKernelInputs`, they become `([256, 256, 640], [640, 256, 256])`. So, my guess is that there's something we should look into before we reach `bindKernelInputs`. Pinging @jjsjann123

**Comment by jjsjann123** [comment] 2022-01-28 21:01
Ha, I saw `expand(40*16, 256, 256)` that doesn't look good.

Let me try to cherry-pick this: https://github.com/pytorch/pytorch/pull/71665 and see if it goes away.

**Comment by jjsjann123** [comment] 2022-01-28 21:51
Loos like it does fix the problem :tada:

**Comment by jjsjann123** [comment] 2022-02-06 18:13
Closing since upstream PR is cherry-picked in #1431

**Closed as completed by jjsjann123** 2022-02-06 18:13 UTC
